---
title: "VisML Lab Week 8"
subtitle: "CS-GY 9223 - Fall 2025 - Final Project Group Formation and Brainstorming"
author: "TBD - Teaching Assistant"
institute: "NYU Tandon School of Engineering"
date: "October 20, 2025"
format:
  revealjs:
    theme: [default, ../../slides/custom.scss]
    slide-number: c/t
    show-slide-number: all
    hash-type: number
    logo: ../../slides/figs/vida.jpg
    width: 1920
    height: 1080
    preview-links: auto
    transition: fade
    transition-speed: fast
    footer: <https://engineering.nyu.edu>
  html:
    code-fold: true
resources:
  - demo.pdf
execute:
  echo: true
jupyter: python3
---

## Lab Overview

* Today: Final Project Group Formation and Brainstorming
* Project proposal workshop
* Research paper analysis activity

## Project Proposal Workshop
* For your project proposal, you will be asked to analyze an existing research paper relevant to your topic 
* This paper will act as a "baseline" for you to compare your work to

## Analyzing a Research Paper
* In groups of 2-3, find a research paper relevant to your interests and discuss the following questions:
  * What were the main novel contributions?
  * Is the work general and reusable or a special case?
  * Are there flaws or neat details in that they did?
  * How does it fit with other papers on similar topics?
  * Does it provoke good questions on further or different things to try? 
* NOTE: You will not be tied to the paper (or people) you pick now for your actual project, but this is a good opportunity to explore ideas for your final project