---
title: "Week 4 Lab: JavaScript Essentials Prior to D3.js"
subtitle: "CS-GY 6313 - Information Visualization"
author: "Ryan Kim"
institute: "New York University"
date: "September 25, 2026"
format:
  revealjs:
    theme: [default, ../slides/custom.scss]
    slide-number: c/t
    show-slide-number: all
    hash-type: number
    logo: ../slides/figs/vida.jpg
    width: 1920
    height: 1080
    preview-links: auto
    transition: fade
    transition-speed: fast
    css: lab-light-theme.css
---

## Week 4 Lab Overview

|User Interface|Graphics Library|Notebook|
|:--|:--|:--|
|[observablehq.com](https://observablehq.com)|[D3](https://d3js.org/)|(none!)|

### Today's Lab Activities

- Introduction to D3.js... kinda
- Introduction to JavaScript Essentials
- Data Manipulation (mapping, filtering)
- DOM Element Selection and Manipulation


## Why JavaScript First?

> **D3.js is mostly JavaScript**. Before we draw anything, it's important to realize that before we even start with D3.js, we have to have a solid grasp on JavaScript fundamentals.

JavaScript is:

- (relatively) lightweight as a standalone language (though the JavaScript ecosystem is getting heavier with each new library released).
- a "Just-In-Time" compiler (<a href="https://developer.mozilla.org/en-US/docs/Glossary/Just_In_Time_Compilation" target="_blank">Read more here</a>).
- used both in and outside of the web browser (e.g. <a href="https://nodejs.org/en" target="_blank">Node.js</a>, <a href="https://react.dev/" target="_blank">React</a>).
- _loosely-typed_ (or _weakly-typed_, _dynamically-typed_, etc.)

---

This is an example of a dataset stored as a JavaScript object - specifically, an array of items.

- The dataset is simply an `Array` storing multiple objects in order.
- Each item in the dataaset is an `Object`
- 

```js
const students = [
  {name: "Alice", major: "CS", score: 82},
  {name: "Bob", major: "Biology", score: 91},
  {name: "Carol", major: "CS", score: 76},
  {name: "David", major: "Physics", score: 88}
];
```

Follow the instructions outlined in today's [Observable Notebook](https://observablehq.com/@rk2546/2025-infovis-cse_week-4-lab).

## End of Lab

- Exercise #4 will be posted no later than **September 28, 2025**.
- Exercise #4 is due on **October 2nd, 2025 @ 11:59pm**!
- Where do I ask questions?
  - TA Office Hours: 
    - Physical Location: Wednesdays @ 2PM-3PM, 8th floor common area @ 370 Jay Street, Brooklyn
    - Online Zoom: [https://nyu.zoom.us/j/92815268504](https://nyu.zoom.us/j/92815268504)
  - Grader TA Office Hours:
    - Online Zoom: [https://nyu.zoom.us/j/2817596431](https://nyu.zoom.us/j/2817596431) 
  - Our course Discord!