---
title: "Welcome back to the Visualization for Machine Learning Lab!"
subtitle: "Week 8: Final Project Group Formation and Brainstorming"
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
  html:
    code-fold: true
resources:
  - demo.pdf
execute:
  echo: true
jupyter: python3
---

## Miscellaneous 

* Homework 3 is due TONIGHT (3/15) at 11:59pm
* Homework 2 grades have been posted, please direct any questions about your specific grade to Rithwick ([rg4361@nyu.edu](rg4361@nyu.edu))

## Project Proposal Workshop
* For your project proposal, you will be asked to analyze an existing research paper relevant to your topic 
* This paper will act as a "baseline" for you to compare your work to

## Analyzing a Research Paper
* In groups of 2-3, find a research paper relevant to your interests and discuss the following questions:
  * What were the main novel contributions?
  * Is the work general and reusable or a special case?
  * Are there flaws or neat details in that they did?
  * How does it fit with other papers on similar topics?
  * Does it provoke good questions on further or different things to try? 
* NOTE: You will not be tied to the paper (or people) you pick now for your actual project, but if you want to do the CFP you can absoultely start on that today