project:
  type: book

book:
  title: "Visualization for Machine Learning"
  author: "Erin McGowan, Vitoria Guardieiro, Claudio Silva"
  date: "2024"
  chapters:
    - index.qmd
    - intro.qmd
    - perception_color.qmd
    - model_assessment.qmd
    - white_box.qmd
    - black_box.qmd
    - clustering.qmd
    - TDA.qmd
    - deep_learning.qmd
    - NLP.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



