"""Derive the presentation data for the week 3 D3 charts from the raw Statcast CSV.

Run:  python3 make_skubal_data.py   (needs pandas)   ->  writes skubal-statcast.js
The charts load skubal-statcast.js via a <script> tag (works from file:// and the web);
fetch()/d3.json() would fail when the rendered HTML is opened from disk.
"""
import json, pandas as pd
from pathlib import Path
here = Path(__file__).parent
df = pd.read_csv(here / "tarik_skubal_statcast_2026-08-08_to_2026-09-07.csv", low_memory=False)
types = ["4-Seam Fastball", "Sinker", "Changeup", "Slider", "Curveball"]
short = {"4-Seam Fastball": "4-Seam"}
sh = lambda t: short.get(t, t)
bar = [{"category": t, "count": int((df.pitch_name == t).sum())} for t in types]
bar.sort(key=lambda d: -d["count"])
ff = df[df.pitch_name == "4-Seam Fastball"].groupby("inning")["release_speed"].agg(["mean", "count"])
line4seam = [{"inning": int(i), "speed": round(float(r["mean"]), 1), "n": int(r["count"])} for i, r in ff.iterrows()]
sc = df[["release_speed", "release_spin_rate", "pitch_name"]].dropna()
med = df.groupby("pitch_name")["release_speed"].median()
medianSpeed = [{"type": t, "speed": round(float(med[t]), 1)} for t in types]
scatter = [{"speed": round(float(r.release_speed), 1), "spin": int(r.release_spin_rate), "type": sh(r.pitch_name)} for r in sc.itertuples()]
df["count"] = df.balls.astype(int).astype(str) + "-" + df.strikes.astype(int).astype(str)
cols = [f"{b}-{s}" for s in (0, 1, 2) for b in (0, 1, 2, 3)]
tab = pd.crosstab(df.pitch_name, df["count"], normalize="columns").mul(100).reindex(index=types, columns=cols).fillna(0)
n = df["count"].value_counts().reindex(cols).fillna(0).astype(int)
cells = [{"count": c, "strikes": int(c[-1]), "type": sh(t), "value": round(float(tab.loc[t, c]), 1), "n": int(n[c])} for c in cols for t in types]
out = {"source": "Tarik Skubal, Statcast (Baseball Savant), 5 games Aug 10 - Sep 3 2026, 495 pitches",
       "bar": bar, "line4seam": line4seam, "medianSpeed": medianSpeed, "scatter": scatter, "heatmap": {"cols": cols, "cells": cells}}
js = "// Generated by make_skubal_data.py from the Statcast CSV in this directory. Do not edit by hand.\nwindow.SKUBAL = " + json.dumps(out, separators=(",", ":")) + ";\n"
(here / "skubal-statcast.js").write_text(js)
print(f"wrote skubal-statcast.js: {len(js)//1024} KB, scatter={len(scatter)}, heatmap cells={len(cells)}")
